### ISSUE TITLE
pthread not required in ./configure

### ISSUE THREAD

**Issue by lynxoid** [mavam/libbf#15]
Getting this error during make after configure succeeded:

```
Linking CXX executable bf-test
CMakeFiles/bf-test.dir/tests.cpp.o: In function `caf::test::watchdog::start(int)':
tests.cpp:(.text+0x5cd2): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```

(Travis CI Ubuntu/Linaro 4.6.3-1ubuntu5 w/ g++4.9)

**Comment by mavam** [comment]
I think I've fixed the issue. Let me know if this is not the case.

Unfortunately some unit tests still fail. I'm planning to rewrite major parts of the library soon. Stay tuned.
