### ISSUE TITLE
aux is a reserved file name on windows

### ISSUE THREAD

**Issue by Rastaban** [mavam/libbf#44]
Please consider renaming the `aux` directory, as that creates a folder that is comically difficult to delete on a windows machine.

from https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file

> Do not use the following reserved names for the name of a file:
> 
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by mavam** [comment]
Thanks for pointing this out.

I'm happy to review and merge PRs that provide a fix. Personally, I would just remove all the contents in `aux`; I doubt anyone uses what's buried in there.

**Comment by egorpugin** [comment]
Same error for me.
Please, fix, thank you.

**Comment by egorpugin** [comment]
See https://github.com/mavam/libbf/pull/45
