### ISSUE TITLE
How to use the library

### ISSUE THREAD

**Issue by FearlessSong** [mavam/libbf#57]
For linux, after installing. U can copy the "bf" floder to the "/usr/include". 
After that, if u want to use this library in ur project.
1. `#include <bf/all.hpp>`
2. copy the libbf.a to the project floder
then :
'gcc main.cpp libbf.a -o main'

**Comment by mavam** [comment]
Thanks for providing these instructions. If you feel the README could be improved, I'm open to PRs.

Unfortunately I don't have the bandwidth to maintain the project, so please feel free to use what you find here.
